apiVersion: v1
kind: Pod
metadata:
  name: pod-env-example
spec:
  containers:
  - name: nginx
    image: nginx:stable-alpine
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
    env:
    - name: MYVAR
      value: isAwesome
    command: ["/bin/sh", "-c"]
    args: ["echo ${MYVAR}"]

